### ISSUE TITLE
Athom Smart plug v3: Can't update to ESPHOME 2024.6.3 - Only one instance of the esphome ota platform is allowed per port

### ISSUE THREAD

**Issue by mishomvp** [athom-tech/esp32-configs#11]
Hello,

When  i am trying to update to ESPHOME 2024.6.3:

INFO ESPHome 2024.6.3
INFO Reading configuration /config/esphome/athom-smart-plug-v3-f8b838.yaml...
Failed config

ota.esphome: [source /data/packages/105b961e/athom-smart-plug.yaml:49]
  
  Only one instance of the esphome ota platform is allowed per port. Note that this error may result from OTA specified in packages.
  platform: esphome
  version: 2
  port: 3232

Because in my configuration:

ota:
  - platform: esphome
    version: 2
    password: "somesecurepassword"

If i remove line:   - platform: esphome
Then can't compile again. 

Only works when configurations looks like:
ota:
    platform: esphome
    version: 2
    password: "somesecurepassword"

Whole configuration:
substitutions:
  name: athom-smart-plug-v3-f8b838
  friendly_name: 1 Athom Plug V3 f8b838
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: hidden

ota:
    platform: esphome
    version: 2
    password: "somesecurepasswd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

**Comment by Roving-Ronin** [comment]
@mishomvp,l
This was an issue in ESPHome itself, not the Athom yaml, see: https://github.com/esphome/esphome/pull/7001
This issue has been fixed with the release of ESPHome 2024.6.4.
